### ISSUE TITLE
Unable to open with PowerPoint 2016

### ISSUE THREAD

**Issue by MitchDresdner** [njcaruso/bot-nodejs-demo#1]
Hello Nick, any chance you can save the PowerPoint presentation as a PDF?

PowerPoint 2016 refuses to open the Bots.pptx file, making a silly suggestion about disabling some security measures.

>The presentation cannot be opened. Your antivirus program may prevent you from opening the presentation. To fix this problem, make sure your antivirus program is current and working correctly. If the problem persists and the presentation is from someone that you trust, turn off your antivirus program, and then try to open the presentation again. If you do this, make sure you turn on your antivirus program again after you open the presentation.

Thanks,

Mitch

**Comment by njcaruso** [comment]
Hi Mitch.  I uploaded the PDF.  I'm giving another presentation on Thursday, so I will probably update both the PPT and PDF as well.

**Comment by MitchDresdner** [comment]
Awesome, thanks Nick!
